#include "gl_extensions.h"
#include <stdio.h>

/* Global function pointer definitions */
PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB = NULL;
PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB = NULL;

PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = NULL;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray = NULL;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = NULL;

PFNGLGENBUFFERSPROC glGenBuffers = NULL;
PFNGLBINDBUFFERPROC glBindBuffer = NULL;
PFNGLBUFFERDATAPROC glBufferData = NULL;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = NULL;

PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers = NULL;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D = NULL;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus = NULL;
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer = NULL;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer = NULL;

PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers = NULL;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer = NULL;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage = NULL;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample = NULL;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers = NULL;

PFNGLCREATESHADERPROC glCreateShader = NULL;
PFNGLSHADERSOURCEPROC glShaderSource = NULL;
PFNGLCOMPILESHADERPROC glCompileShader = NULL;
PFNGLDELETESHADERPROC glDeleteShader = NULL;
PFNGLGETSHADERIVPROC glGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = NULL;

PFNGLCREATEPROGRAMPROC glCreateProgram = NULL;
PFNGLATTACHSHADERPROC glAttachShader = NULL;
PFNGLLINKPROGRAMPROC glLinkProgram = NULL;
PFNGLUSEPROGRAMPROC glUseProgram = NULL;
PFNGLDELETEPROGRAMPROC glDeleteProgram = NULL;
PFNGLGETPROGRAMIVPROC glGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = NULL;

PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = NULL;
PFNGLUNIFORM1IPROC glUniform1i = NULL;
PFNGLUNIFORM1FPROC glUniform1f = NULL;
PFNGLUNIFORM3FPROC glUniform3f = NULL;
PFNGLUNIFORM3FVPROC glUniform3fv = NULL;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = NULL;

PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = NULL;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = NULL;

PFNGLGENERATEMIPMAPPROC glGenerateMipmap = NULL;
PFNGLACTIVETEXTUREPROC glActiveTexture = NULL;
PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample = NULL;

/* Helper macro for loading function pointers */
#define LOAD_GL_FUNC(func_type, func_name) \
    do { \
        func_name = (func_type)wglGetProcAddress(#func_name); \
        if (!func_name) { \
            fprintf(stderr, "Failed to load OpenGL function: %s\n", #func_name); \
            return false; \
        } \
    } while(0)

bool gl_load_extensions(void) {
    /* WGL Functions */
    LOAD_GL_FUNC(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);
    LOAD_GL_FUNC(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB);

    /* Vertex Array Objects */
    LOAD_GL_FUNC(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
    LOAD_GL_FUNC(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
    LOAD_GL_FUNC(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays);

    /* Buffer Objects */
    LOAD_GL_FUNC(PFNGLGENBUFFERSPROC, glGenBuffers);
    LOAD_GL_FUNC(PFNGLBINDBUFFERPROC, glBindBuffer);
    LOAD_GL_FUNC(PFNGLBUFFERDATAPROC, glBufferData);
    LOAD_GL_FUNC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);

    /* Framebuffer Objects */
    LOAD_GL_FUNC(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers);
    LOAD_GL_FUNC(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer);
    LOAD_GL_FUNC(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D);
    LOAD_GL_FUNC(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers);
    LOAD_GL_FUNC(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus);
    LOAD_GL_FUNC(PFNGLBLITFRAMEBUFFERPROC, glBlitFramebuffer);
    LOAD_GL_FUNC(PFNGLFRAMEBUFFERRENDERBUFFERPROC, glFramebufferRenderbuffer);

    /* Renderbuffer Objects */
    LOAD_GL_FUNC(PFNGLGENRENDERBUFFERSPROC, glGenRenderbuffers);
    LOAD_GL_FUNC(PFNGLBINDRENDERBUFFERPROC, glBindRenderbuffer);
    LOAD_GL_FUNC(PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC, glRenderbufferStorageMultisample);
    LOAD_GL_FUNC(PFNGLDELETERENDERBUFFERSPROC, glDeleteRenderbuffers);

    /* Shader Objects */
    LOAD_GL_FUNC(PFNGLCREATESHADERPROC, glCreateShader);
    LOAD_GL_FUNC(PFNGLSHADERSOURCEPROC, glShaderSource);
    LOAD_GL_FUNC(PFNGLCOMPILESHADERPROC, glCompileShader);
    LOAD_GL_FUNC(PFNGLDELETESHADERPROC, glDeleteShader);
    LOAD_GL_FUNC(PFNGLGETSHADERIVPROC, glGetShaderiv);
    LOAD_GL_FUNC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);

    /* Program Objects */
    LOAD_GL_FUNC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
    LOAD_GL_FUNC(PFNGLATTACHSHADERPROC, glAttachShader);
    LOAD_GL_FUNC(PFNGLLINKPROGRAMPROC, glLinkProgram);
    LOAD_GL_FUNC(PFNGLUSEPROGRAMPROC, glUseProgram);
    LOAD_GL_FUNC(PFNGLDELETEPROGRAMPROC, glDeleteProgram);
    LOAD_GL_FUNC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
    LOAD_GL_FUNC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);

    /* Uniform Variables */
    LOAD_GL_FUNC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
    LOAD_GL_FUNC(PFNGLUNIFORM1IPROC, glUniform1i);
    LOAD_GL_FUNC(PFNGLUNIFORM1FPROC, glUniform1f);
    LOAD_GL_FUNC(PFNGLUNIFORM3FPROC, glUniform3f);
    LOAD_GL_FUNC(PFNGLUNIFORM3FVPROC, glUniform3fv);
    LOAD_GL_FUNC(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv);

    /* Vertex Attributes */
    LOAD_GL_FUNC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
    LOAD_GL_FUNC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);

    /* Texture Functions */
    LOAD_GL_FUNC(PFNGLGENERATEMIPMAPPROC, glGenerateMipmap);
    LOAD_GL_FUNC(PFNGLACTIVETEXTUREPROC, glActiveTexture);
    LOAD_GL_FUNC(PFNGLTEXIMAGE2DMULTISAMPLEPROC, glTexImage2DMultisample);

    return true;
}
